context:
  version: "0.5.3"

package:
  name: tex-fmt
  version: ${{ version }}

source:
  url: https://github.com/WGUNDERWOOD/tex-fmt/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 39a7cfc857a6babced169ce3b61fe506346fdc938165aa836ecb570421634ed2

build:
  number: 0
  script:
    env:
      CARGO_PROFILE_RELEASE_STRIP: symbols
      CARGO_PROFILE_RELEASE_LTO: thin
    content:
      - cargo-bundle-licenses --format yaml --output ${{ "%SRC_DIR%" if win else "$SRC_DIR" }}/THIRDPARTY.yml
      - ${{ "export LD_LIBRARY_PATH=$PREFIX/lib" if unix }}
      - cargo install --no-track --locked --bins --root ${{ "%LIBRARY_PREFIX%" if win else "$PREFIX" }} --path .

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses
  host:
    - ${{ "zlib" if unix }}

tests:
  - script:
      - tex-fmt --help

about:
  homepage: https://github.com/WGUNDERWOOD/tex-fmt
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  description: "LaTeX formatter written in Rust."
  summary: "LaTeX formatter written in Rust."

extra:
  recipe-maintainers:
    - tetov
